[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/golang/glog"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.ibm.com/FSaaS/csi-iscsi"

[[constraint]]
  branch = "master"
  name = "github.ibm.com/FSaaS/scale-image"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"
  #branch = "release-branch.go1.10"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.15.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

# Transitive dependency of k8s.io/kubernetes/pkg/util/parsers
[[override]]
  #branch = "master"
  version = "2.7.0-rc.0"
  name = "github.com/docker/distribution"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=1.13.3"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.3"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.3"

# Transitive dependency of CSI Spec
#[[override]]
#  name = "github.com/golang/protobuf"
#  version = "1.1.0"

