--- 
- name: Ensure secret {{ item.secrets }} defined in {{ lookup( 'vars','namespace' ) }}
  k8s_facts:
    kind: secrets
    namespace: "{{ lookup( 'vars','namespace' ) }}"
    name : "{{ item.secrets }}"
  register: results
  failed_when: results is not defined or results.results is not defined or (results.results|length==0)

- name: "Label unlabled secrets"
  include_tasks: password_label.yml
  when: item.metadata.label is not defined or
    item.metadata.label["app.kubernetes.io/name"] is not defined or
    item.metadata.label["app.kubernetes.io/name"] != "ibm-spectrum-scale-csi-operator"
  loop:  "{{ results.resources }}"

# Hash using a salted 
- name: "Build Secret Checksum"
  set_fact: 
    secret_checksums: "{{ secret_checksums +  [ (results.resources[0].data | default(' ')) | to_json | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) ] }}"





